### PR TITLE
add Bors config file

### PR DESCRIPTION
**Pull request by fharper**

### CODE REVIEW

**Comment by fharper** [comment]
Put you @curquiza as reviewer since my team doesn't know Bors as much as you :D

**Comment by curquiza** [comment]
Bors is only useful if you have tests ^^ so not here if I'm not wrong.
Plus, I'm not sure this is useful to add this kind of tool on a repo that will not get a lot of PRs related to the codebase. This is useful for repos where devs simultaneously contribute to the codebase -> it avoids asking everybody to rebase after each PR merged.

**Comment by fharper** [comment]
I'm not putting aside the fact of having test for the demos, but ok, I thought we wanted to use Bors as much as possible. Thanks :)

**Comment by curquiza** [comment]
You can put bors where you want, but tests are mandatory otherwise bors is completely pointless.

**Pull request closed without merging**
